version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurante-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurante-db"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurante-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_ERROR_INCLUDE_MESSAGE: "always"
      TZ: America/Sao_Paulo
      JAVA_TOOL_OPTIONS: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=75"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
