spring:
  application:
    name: restauranteapp
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.techchallenge.restauranteapp: DEBUG
