spring:
  datasource:
    url: jdbc:postgresql://db:5432/restaurante-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: RestauranteHikari
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
